### PR TITLE
update demo content and little more cleanup

### PR DESCRIPTION
**Pull request by wburgers**
Moved some css to the google-slide element
Updated the demo content to point to 1.0 content

Want to get rid of animate.css, but it is hard to select the slide h1
and p elements for animation in js

### CODE REVIEW

**Comment by wburgers** [comment]
Hi,

I updated the demo content and removed some css that was not really relevant.
I wanted to animate the slide h1 and p with neon animations instead of the animate.css file, but I couldn't figure out how to select them after they were distributed as &lt;content&gt; elements in the google-slide element.
Maybe you can check that out?

Anyway, hope you like the content!

Best regards and have a nice weekend!

Willem

**Comment by wburgers** [comment]
Hi @addyosmani,

Did you already check this PR?
Let me know what you think about it.

Best regards,
Willem

**Comment by addyosmani** [comment]
This is much much better. Thanks for taking the time to clean this up. I greatly appreciate it.

**Comment by wburgers** [comment]
No problem!
Happy to contribute 😊.

Do you know if the new features in polymer 1.2 will help in selecting elements distributed by &lt;content&gt;?
I believe the polymer.dom() function was extended to do this, but I didn't check it yet.
Maybe this will help in getting rid of the animate.CSS file.

Let me know what you think.

**Pull request merged**
