### PR TITLE
Update to Polymer 1.0 and use platinum-sw for offline

### LINKED ISSUE #5: Rewrite for Polymer 0.8
We're blocked on this until core-animated-pages gets ported over, but it would be good to rewrite and solve some of the existing issues with it at the same time.

### PR DESCRIPTION
**Pull request by wburgers**
Can't get the animations to display properly, but I haven't checked in detail either, so maybe you know how to update that with neon animatable slides.

The rest is working pretty sweet.

This should fix #5...

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for working on this @wburgers!

**Comment by addyosmani** [comment]
Tested locally. As you mentioned, everything seems to be working fine other than the transitions. The original effect used was similar to what is currently demoed over on https://elements.polymer-project.org/elements/neon-animation?view=demo:demo/index.html&active=neon-animated-pages.

This relies on `neon-animated-pages` `slide-from-n-animation` and `slide-from-n` for the `entryAnimation` and `exitAnimation`. It's something like:

```js
      var scope = document.querySelector('template[is="dom-bind"]');
      scope.selected = 0;
      scope._onPrevClick = function() {
        this.entryAnimation = 'slide-from-left-animation';
        this.exitAnimation = 'slide-right-animation';
        this.selected = this.selected === 0 ? 4 : (this.selected - 1);
      }
      scope._onNextClick = function() {
        this.entryAnimation = 'slide-from-right-animation';
        this.exitAnimation = 'slide-left-animation';
        this.selected = this.selected === 4 ? 0 : (this.selected + 1);
      }
```

Configuring `entry-animation` and `exit-animation` should give us the final piece we're after: 

```js
entry-animation="[[entryAnimation]]" exit-animation="[[exitAnimation]]"
```

**Comment by wburgers** [comment]
Cool, that worked!
I tried something like that, but didn't get the details right I guess.
Thanks @addyosmani!

I also used one way bindings in the author element :-).

One more remark though, I tried data binding the visibility of the next and previous buttons to the 'hidden' dom attribute.
something like <paper-fab id="preBtn" hidden$="{{_computePreBtn()}}" ... >
That would lose some more lines of JS such that it becomes more declarative, but that does not work for some reason.
I tried it with and without an argument to the function as well as bind to the parent div of the paper-fab.
Do you know why that does not work?

**Comment by wburgers** [comment]
Never mind that compute binding, got that working as well ;-)

**Comment by addyosmani** [comment]
Awesome! Do you want to go ahead and squash commits and we can land this? :rocket:

**Comment by wburgers** [comment]
Done @addyosmani
Thanks again for your help
Maybe I'll get to the demo content and the gh-pages branch in the weekend.
I'll let you know :+1:

**Comment by addyosmani** [comment]
:stars: :cake:

**Comment by addyosmani** [comment]
@wburgers just noticed while looking at the demo source that we should probably also update it to reference the 1.0 elements rather than `core-*` etc. Filed a bug to track https://github.com/addyosmani/google-slides/issues/7

**Comment by wburgers** [comment]
@addyosmani that is what I meant with demo content.
I hope to get to it this weekend.
In between fixing the printer for my parents and helping my mom with her new phone :stuck_out_tongue:

**Pull request merged**
